### ISSUE TITLE
[Feature] DiscordSRV support

### ISSUE THREAD

**Issue by Dyljyn** [kennytv/Maintenance#135]
I was wondering if support for [DiscordSRV](https://modrinth.com/plugin/discordsrv) could be considered. This would allow the fact that the server is in maintenance mode be automatically broadcasted and displayed in the associated Discord server.

**Comment by PSYCHEER** [comment]
+1

**Comment by kennytv** [comment]
Depending on what exactly you want, you should be able to use `commands-on-maintenance-enable` and `commands-on-maintenance-disable` to just run discordsrv commands there

**Comment by FaultyFunctions** [comment]
You could also do the opposite. In DiscordSRV you can use `alerts.yml` to send whatever messages you want when maintenance is enabled/disabled.

For example:
```yaml
  - Trigger: MaintenanceChangedEvent
    Channel: WhateverChannelYouHaveLinkedAndWantHere
    Embed:
      Color: "#000001"
      Author:
        ImageUrl: "LinkToWhateverImageYouWant.png"
        Name: '${#event.isMaintenance() ? "Server is now under maintenance!" : "Server maintenance is over!"}'
```

I haven't personally tested this, but I think it'll work.
