### ISSUE TITLE
[Velocity] Maintenance MOTD incorrectly propagates to all servers sharing the same forced host configuration

### ISSUE THREAD

**Issue by alec-jensen** [kennytv/Maintenance#156]
When a specific server under a proxy is under maintenance, and there are multiple servers under a single forced host, all of those servers will pick up the maintenance MOTD even if they are the primary server on a different forced host. This is because we are checking for all servers under a forced host, not the current active server. This is totally my fault and was added in #118 

## Bug reproducibility
Consider a forced hosts like such:
```toml
[forced-hosts]
	"lobby.example.com" = ["lobby", "limbo"]
	"smp.example.com" = ["smp", "lobby", "limbo"]
```
Put the lobby server under maintenance. The smp server will also show the maintenance MOTD. However, the smp server is still joinable as this ONLY affects the MOTD.

## Error
No relevant errors

## Server information
https://pastes.dev/YNY3iaK7Da

If I have time I might open a PR to fix this

EDIT: Updated issue to more accurately reflect the bug.
